### PR TITLE
encode html entities for char-nodes

### PR DESCRIPTION
**Pull request by pYr0x**
this should fix the issue that html entities were not encoded.
https://github.com/canjs/can-simple-dom/issues/19
https://github.com/donejs/done-ssr/issues/181

i added 'he' as @m-mujica mention.

if no one has objection @matthewp @justinbmeyer @DesignByOnyx  i will merge that PR

encode html entities for char-nodes and title and alt attributes
(cherry picked from commit 7397af2)

### CODE REVIEW

**Comment by matthewp** [comment]
lgtm

**Comment by pYr0x** [comment]
@justinbmeyer also for you?

**Comment by justinbmeyer** [comment]
Out this weekend. Will check Monday.

**Comment by pYr0x** [comment]
Ok, thank you

**Comment by pYr0x** [comment]
@justinbmeyer any thoughts?

**Comment by pYr0x** [comment]
@daffl could you please merge that and make a patch release... thx

**Comment by matthewp** [comment]
Released as 1.0.1

**Pull request merged**
